import { Exam, Question, PetStandard, PetLogEntry, DescriptiveSubmission, LeaderboardRank, UserProfile, PreviousPaper, UserAttempt, SubjectPerformance } from './types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_candidate_9921',
  name: 'Vasu Reddy',
  email: 'vasu.si.aspirant@gmail.com',
  phone: '9848022338',
  role: 'STUDENT',
  targetState: 'TELANGANA',
  targetExam: 'TSLPRB_SI_CIVIL_AR',
  primaryLanguage: 'TELUGU',
  gender: 'MALE',
  subscriptionTier: 'PREMIUM',
  rollNumber: 'TS-SI-2026-8841',
  registeredAt: '2026-08-15',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
};

export const ADMIN_USER: UserProfile = {
  id: 'usr_admin_001',
  name: 'Dr. K. Srinivas Rao, IPS (Retd.)',
  email: 'director@policesi-academy.gov.in',
  phone: '9440112233',
  role: 'ADMIN',
  targetState: 'TELANGANA',
  targetExam: 'TSLPRB_SI_CIVIL_AR',
  primaryLanguage: 'ENGLISH',
  gender: 'MALE',
  subscriptionTier: 'PREMIUM',
  rollNumber: 'ADM-BOARD-01',
  registeredAt: '2026-01-01',
};

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: 'q_pwt_01',
    subject: 'Indian Polity & Constitution',
    topic: 'Fundamental Rights & Police Powers',
    questionText: 'Which Article of the Indian Constitution provides safeguards against arbitrary arrest and detention by law enforcement authorities?',
    questionTextTelugu: 'చట్టాన్ని అమలు చేసే అధికారులచే ఏకపక్ష అరెస్టు మరియు నిర్బంధానికి వ్యతిరేకంగా భారత రాజ్యాంగంలోని ఏ అధికరణ రక్షణ కల్పిస్తుంది?',
    questionTextHindi: 'भारतीय संविधान का कौन सा अनुच्छेद कानून प्रवर्तन अधिकारियों द्वारा मनमाने ढंग से गिरफ्तारी और हिरासत के खिलाफ सुरक्षा प्रदान करता है?',
    questionTextUrdu: 'ہندوستانی آئین کا کون سا آرٹیکل قانون نافذ کرنے والے اداروں کی طرف سے من مانی گرفتاری اور حراست سے تحفظ فراہم کرتا ہے؟',
    options: [
      { key: 'A', text: 'Article 20', textTelugu: 'ఆర్టికల్ 20', textHindi: 'अनुच्छेद 20', textUrdu: 'آرٹیکل 20' },
      { key: 'B', text: 'Article 22', textTelugu: 'ఆర్టికల్ 22', textHindi: 'अनुच्छेद 22', textUrdu: 'آرٹیکل 22' },
      { key: 'C', text: 'Article 21', textTelugu: 'ఆర్టికల్ 21', textHindi: 'अनुच्छेद 21', textUrdu: 'آرٹیکل 21' },
      { key: 'D', text: 'Article 24', textTelugu: 'ఆర్టికల్ 24', textHindi: 'अनुच्छेद 24', textUrdu: 'آرٹیکل 24' },
    ],
    correctAnswer: 'B',
    explanation: 'Article 22 of the Constitution provides protection against arrest and detention in certain cases, mandating that an arrested person must be produced before the nearest magistrate within 24 hours.',
    explanationTelugu: 'రాజ్యాంగంలోని అధికరణ 22 అరెస్టు మరియు నిర్బంధం నుండి రక్షణ కల్పిస్తుంది. అరెస్టు చేయబడిన వ్యక్తిని 24 గంటలలోపు సమీప మేజిస్ట్రేట్ ముందు హాజరుపరచాలని ఇది నిర్దేశిస్తుంది.',
    explanationHindi: 'संविधान का अनुच्छेद 22 कुछ मामलों में गिरफ्तारी और हिरासत के खिलाफ संरक्षण प्रदान करता है, जिसके तहत 24 घंटे के भीतर निकटतम मजिस्ट्रेट के समक्ष पेश करना अनिवार्य है।',
    explanationUrdu: 'آئین کا آرٹیکل 22 گرفتاری اور حراست سے تحفظ فراہم کرتا ہے، جس میں 24 گھنٹے کے اندر مجسٹریٹ کے سامنے پیش کرنا لازمی ہے۔',
    difficulty: 'MEDIUM',
    marks: 1,
    negativeMarks: 0.25,
  },
  {
    id: 'q_pwt_02',
    subject: 'Arithmetic',
    topic: 'Time and Distance (Police Chasing Thief)',
    questionText: 'A police officer starts chasing a thief from a distance of 200 meters. The thief runs at 10 km/h and the police officer runs at 12 km/h. At what distance will the police officer catch the thief?',
    questionTextTelugu: 'ఒక పోలీసు అధికారి 200 మీటర్ల దూరం నుండి దొంగను వెంబడించడం ప్రారంభిస్తాడు. దొంగ వేగం గంటకు 10 కి.మీ మరియు పోలీసు అధికారి వేగం గంటకు 12 కి.మీ. ఎంత దూరం తర్వాత పోలీసు అధికారి దొంగను పట్టుకుంటాడు?',
    questionTextHindi: 'एक पुलिस अधिकारी 200 मीटर की दूरी से चोर का पीछा करता है। चोर 10 किमी/घंटा और पुलिसकर्मी 12 किमी/घंटा की गति से दौड़ता है। पुलिस अधिकारी कितनी दूरी पर चोर को पकड़ेगा?',
    questionTextUrdu: 'ایک پولیس اہلکار 200 میٹر کے فاصلے سے چور کا پیچھا کرتا ہے۔ چور 10 کلومیٹر فی گھنٹہ اور پولیس اہلکار 12 کلومیٹر فی گھنٹہ کی رفتار سے دوڑتا ہے۔ پولیس اہلکار کتنے فاصلے پر چور کو پکڑے گا؟',
    options: [
      { key: 'A', text: '1000 meters (1.0 km)', textTelugu: '1000 మీటర్లు (1.0 కి.మీ)', textHindi: '1000 मीटर (1.0 किमी)', textUrdu: '1000 میٹر (1.0 کلومیٹر)' },
      { key: 'B', text: '1200 meters (1.2 km)', textTelugu: '1200 మీటర్లు (1.2 కి.మీ)', textHindi: '1200 मीटर (1.2 किमी)', textUrdu: '1200 میٹر (1.2 کلومیٹر)' },
      { key: 'C', text: '800 meters (0.8 km)', textTelugu: '800 మీటర్లు (0.8 కి.మీ)', textHindi: '800 मीटर (0.8 किमी)', textUrdu: '800 میٹر (0.8 کلومیٹر)' },
      { key: 'D', text: '1500 meters (1.5 km)', textTelugu: '1500 మీటర్లు (1.5 కి.మీ)', textHindi: '1500 मीटर (1.5 किमी)', textUrdu: '1500 میٹر (1.5 کلومیٹر)' },
    ],
    correctAnswer: 'B',
    explanation: 'Relative speed = (12 - 10) km/h = 2 km/h = 2 * (5/18) = 5/9 m/s. Time to cover 200m = 200 / (5/9) = 360 seconds. Distance covered by police officer = speed * time = 12 * (5/18) * 360 = 1200 meters.',
    explanationTelugu: 'సాపేక్ష వేగం = (12 - 10) = 2 కి.మీ/గం = 2 * (5/18) = 5/9 మీ/సె. 200 మీటర్లను అధిగమించడానికి పట్టే సమయం = 200 / (5/9) = 360 సెకన్లు. పోలీసు ప్రయాణించిన దూరం = 12 * (5/18) * 360 = 1200 మీటర్లు.',
    explanationHindi: 'सापेक्ष गति = (12 - 10) = 2 किमी/घं = 5/9 मी/सेकंड। समय = 200 / (5/9) = 360 सेकंड। तय दूरी = 12 * (5/18) * 360 = 1200 मीटर।',
    explanationUrdu: 'نسبتی رفتار = 2 کلومیٹر فی گھنٹہ = 5/9 میٹر فی سیکنڈ۔ وقت = 360 سیکنڈ۔ فاصلہ = 1200 میٹر۔',
    difficulty: 'MEDIUM',
    marks: 1,
    negativeMarks: 0.25,
  },
  {
    id: 'q_pwt_03',
    subject: 'Test of Reasoning',
    topic: 'Coding - Decoding',
    questionText: 'In a certain military code, if "POLICE" is coded as "QPMJDF", how will "PATROL" be coded in the same pattern?',
    questionTextTelugu: 'ఒక నిర్దిష్ట కోడ్ విధానంలో "POLICE" ను "QPMJDF" గా రాస్తే, అదే కోడ్‌లో "PATROL" ను ఎలా రాస్తారు?',
    questionTextHindi: 'यदि किसी सैन्य कोड में "POLICE" को "QPMJDF" लिखा जाता है, तो उसी पैटर्न में "PATROL" को क्या लिखा जाएगा?',
    questionTextUrdu: 'اگر کسی فوجی کوڈ میں "POLICE" کو "QPMJDF" لکھا جاتا ہے، تو اسی پیٹرن میں "PATROL" کو کیسے لکھا جائے گا؟',
    options: [
      { key: 'A', text: 'QBUSPM', textTelugu: 'QBUSPM', textHindi: 'QBUSPM', textUrdu: 'QBUSPM' },
      { key: 'B', text: 'QBSUOM', textTelugu: 'QBSUOM', textHindi: 'QBSUOM', textUrdu: 'QBSUOM' },
      { key: 'C', text: 'QCVSPM', textTelugu: 'QCVSPM', textHindi: 'QCVSPM', textUrdu: 'QCVSPM' },
      { key: 'D', text: 'QBURPN', textTelugu: 'QBURPN', textHindi: 'QBURPN', textUrdu: 'QBURPN' },
    ],
    correctAnswer: 'A',
    explanation: 'Each letter is shifted by +1 in the alphabet forward: P->Q, A->B, T->U, R->S, O->P, L->M. Hence, PATROL becomes QBUSPM.',
    explanationTelugu: 'ప్రతి అక్షరం వర్ణమాలలో +1 ముందుకు మారుతుంది: P->Q, A->B, T->U, R->S, O->P, L->M. కావున సమాధానం QBUSPM.',
    explanationHindi: 'प्रत्येक अक्षर को वर्णमाला में +1 आगे बढ़ाया गया है। अतः PATROL बन जाता है QBUSPM।',
    explanationUrdu: 'ہر حرف کو انگریزی حروف تہجی میں ایک قدم آگے بڑھایا گیا ہے۔ اس لیے PATROL بن جاتا ہے QBUSPM۔',
    difficulty: 'EASY',
    marks: 1,
    negativeMarks: 0.25,
  },
  {
    id: 'q_pwt_04',
    subject: 'History & State Movement',
    topic: 'Telangana & Andhra Pradesh Reorganization',
    questionText: 'Under the Andhra Pradesh Reorganisation Act, 2014, which section provided for the distribution of Police personnel between Telangana and Andhra Pradesh?',
    questionTextTelugu: 'ఆంధ్రప్రదేశ్ పునర్వ్యవస్థీకరణ చట్టం, 2014 ప్రకారం, తెలంగాణ మరియు ఆంధ్రప్రదేశ్ రాష్ట్రాల మధ్య పోలీసు సిబ్బంది కేటాయింపుకు సంబంధించిన సెక్షన్ ఏది?',
    questionTextHindi: 'आंध्र प्रदेश पुनर्गठन अधिनियम, 2014 के तहत, तेलंगाना और आंध्र प्रदेश के बीच पुलिस कर्मियों के आवंटन का प्रावधान किस धारा में है?',
    questionTextUrdu: 'آندھرا پردیش ری آرگنائزیشن ایکٹ 2014 کے تحت، تلنگانہ اور آندھرا پردیش کے درمیان پولیس اہلکاروں کی تقسیم کس سیکشن کے تحت کی گئی؟',
    options: [
      { key: 'A', text: 'Section 77', textTelugu: 'సెక్షన్ 77', textHindi: 'धारा 77', textUrdu: 'سیکشن 77' },
      { key: 'B', text: 'Section 82', textTelugu: 'సెక్షన్ 82', textHindi: 'धारा 82', textUrdu: 'سیکشن 82' },
      { key: 'C', text: 'Section 76', textTelugu: 'సెక్షన్ 76', textHindi: 'धारा 76', textUrdu: 'سیکشن 76' },
      { key: 'D', text: 'Section 90', textTelugu: 'సెక్షన్ 90', textHindi: 'धारा 90', textUrdu: 'سیکشن 90' },
    ],
    correctAnswer: 'A',
    explanation: 'Section 77 of the AP Reorganisation Act, 2014 deals with the allocation and distribution of state government employees, including civil & armed police forces, based on the Kamalanathan Committee guidelines.',
    explanationTelugu: 'ఆంధ్రప్రదేశ్ పునర్వ్యవస్థీకరణ చట్టం, 2014 లోని సెక్షన్ 77 కమలనాథన్ కమిటీ మార్గదర్శకాల ఆధారంగా పోలీసు బలగాలతో సహా ఉద్యోగుల కేటాయింపును సూచిస్తుంది.',
    explanationHindi: 'एपी पुनर्गठन अधिनियम, 2014 की धारा 77 कमलानाथन समिति के दिशानिर्देशों के आधार पर पुलिस बलों सहित कर्मचारियों के आवंटन से संबंधित है।',
    explanationUrdu: 'اے پی ری آرگنائزیشن ایکٹ 2014 کا سیکشن 77 کملا ناتھن کمیٹی کے تحت پولیس ملازمین کی تقسیم سے متعلق ہے۔',
    difficulty: 'HARD',
    marks: 1,
    negativeMarks: 0.25,
  },
  {
    id: 'q_pwt_05',
    subject: 'General Science',
    topic: 'Forensic Science & Ballistics',
    questionText: 'In forensic ballistics, which test is commonly used to detect gunshot residue (GSR) on the hands of a suspect who recently fired a weapon?',
    questionTextTelugu: 'ఫోరెన్సిక్ బాలిస్టిక్స్‌లో, తుపాకీ కాల్చిన అనుమానితుడి చేతులపై గన్‌పౌడర్ అవశేషాలను (GSR) గుర్తించడానికి ఏ పరీక్షను ఉపయోగిస్తారు?',
    questionTextHindi: 'फोरेंसिक बैलिस्टिक में, हाल ही में हथियार चलाने वाले संदिग्ध के हाथों पर गनशॉट अवशेष (GSR) का पता लगाने के लिए किस परीक्षण का उपयोग किया जाता है?',
    questionTextUrdu: 'فرانزک بیلسٹکس میں، ہتھیار چلانے والے مشتبہ شخص کے ہاتھوں پر بارود کے ذرات (GSR) معلوم کرنے کے لیے کون سا ٹیسٹ استعمال ہوتا ہے؟',
    options: [
      { key: 'A', text: 'Dermal Nitrate (Paraffin) Test', textTelugu: 'డెర్మల్ నైట్రేట్ (పారఫిన్) పరీక్ష', textHindi: 'डर्मल नाइट्रेट (पैराफिन) टेस्ट', textUrdu: 'ڈیرمل نائٹریٹ (پیرافین) ٹیسٹ' },
      { key: 'B', text: 'Benedict Test', textTelugu: 'బెనెడిక్ట్ పరీక్ష', textHindi: 'बेनेडिक्ट टेस्ट', textUrdu: 'بینیڈکٹ ٹیسٹ' },
      { key: 'C', text: 'Biuret Test', textTelugu: 'బైయురెట్ పరీక్ష', textHindi: 'बायूरेट टेस्ट', textUrdu: 'بایوریٹ ٹیسٹ' },
      { key: 'D', text: 'Elisa Test', textTelugu: 'ఎలిసా పరీక్ష', textHindi: 'एलिसा टेस्ट', textUrdu: 'ایلیسا ٹیسٹ' },
    ],
    correctAnswer: 'A',
    explanation: 'The Dermal Nitrate (Paraffin) test and Scanning Electron Microscopy with Energy Dispersive X-ray (SEM-EDX) are the recognized forensic techniques for detecting gunshot residue particles.',
    explanationTelugu: 'తుపాకీ కాల్పుల వల్ల చేతులపై ఏర్పడే నైట్రేట్ అవశేషాలను గుర్తించడానికి డెర్మల్ నైట్రేట్ (పారఫిన్) మరియు SEM-EDX పరీక్షలను ఉపయోగిస్తారు.',
    explanationHindi: 'डर्मल नाइट्रेट (पैराफिन) टेस्ट और एसईएम-ईडीएक्स गनशॉट अवशेष कणों का पता लगाने के लिए मान्यता प्राप्त फोरेंसिक तकनीकें हैं।',
    explanationUrdu: 'ڈیرمل نائٹریٹ اور ایس ای ایم-ای ڈی ایکس فرانزک طریقہ کار بندوق کے ذرات معلوم کرنے کے لیے استعمال ہوتے ہیں۔',
    difficulty: 'MEDIUM',
    marks: 1,
    negativeMarks: 0.25,
  }
];

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'tslprb-si-pwt-mock-01',
    title: 'TSLPRB SI Preliminary Written Test (PWT) - Full Grand Mock 1',
    titleTelugu: 'తెలంగాణ ఎస్సై ప్రిలిమినరీ రాత పరీక్ష (PWT) - గ్రాండ్ మాక్ టెస్ట్ 1',
    titleHindi: 'तेलंगाना पुलिस एसआई प्रारंभिक परीक्षा - ग्रैंड मॉक टेस्ट 1',
    titleUrdu: 'تلنگانہ پولیس ایس آئی پرلیمس گرینڈ موک ٹیسٹ 1',
    examType: 'PRELIMS_PWT',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'TELANGANA',
    isPremiumOnly: false,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'tslprb-si-pwt-mock-02',
    title: 'TSLPRB SI Preliminary Written Test (PWT) - Full Grand Mock 2',
    titleTelugu: 'తెలంగాణ ఎస్సై ప్రిలిమినరీ రాత పరీక్ష (PWT) - గ్రాండ్ మాక్ టెస్ట్ 2',
    titleHindi: 'तेलंगाना पुलिस एसआई प्रारंभिक परीक्षा - ग्रैंड मॉक टेस्ट 2',
    titleUrdu: 'تلنگانہ پولیس ایس آئی پرلیمس گرینڈ موک ٹیسٹ 2',
    examType: 'PRELIMS_PWT',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'TELANGANA',
    isPremiumOnly: true,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'ap-si-pwt-mock-01',
    title: 'AP Police SI Preliminary Written Test - Grand Mock Test 1',
    titleTelugu: 'ఆంధ్రప్రదేశ్ పోలీస్ ఎస్సై ప్రిలిమినరీ గ్రాండ్ మాక్ టెస్ట్ 1',
    titleHindi: 'आंध्र प्रदेश पुलिस एसआई प्रारंभिक परीक्षा - ग्रैंड मॉक 1',
    titleUrdu: 'آندھرا پردیش پولیس ایس آئی پرلیمس گرینڈ موک 1',
    examType: 'PRELIMS_PWT',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'ANDHRA_PRADESH',
    isPremiumOnly: true,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'practice-arithmetic-01',
    title: 'Topic Practice: Arithmetic, Ratios & Distance (Police Chasing Problems)',
    titleTelugu: 'టాపిక్ ప్రాక్టీస్: అర్థమెటిక్, సమయం & దూరం (పోలీస్ చేజింగ్ లెక్కలు)',
    titleHindi: 'विषय अभ्यास: अंकगणित, समय और दूरी',
    titleUrdu: 'موضوعاتی مشق: ریاضی، وقت اور فاصلہ',
    examType: 'DAILY_QUIZ',
    durationMins: 30,
    totalMarks: 25,
    totalQuestions: 25,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'ALL_INDIA',
    isPremiumOnly: false,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'practice-polity-01',
    title: 'Topic Practice: Indian Constitution, Fundamental Rights & CrPC / IPC',
    titleTelugu: 'టాపిక్ ప్రాక్టీస్: భారత రాజ్యాంగం, ప్రాథమిక హక్కులు & క్రిమినల్ చట్టాలు',
    titleHindi: 'विषय अभ्यास: भारतीय संविधान एवं पुलिस शक्तियां',
    titleUrdu: 'موضوعاتی مشق: ہندوستانی آئین اور پولیس اختیارات',
    examType: 'DAILY_QUIZ',
    durationMins: 25,
    totalMarks: 20,
    totalQuestions: 20,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'ALL_INDIA',
    isPremiumOnly: false,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'practice-telangana-movement-01',
    title: 'Topic Practice: Telangana Movement, Statehood & AP Reorganisation Act 2014',
    titleTelugu: 'టాపిక్ ప్రాక్టీస్: తెలంగాణ ఉద్యమం, రాష్ట్ర ఆవిర్భావం & పునర్వ్యవస్థీకరణ చట్టం',
    titleHindi: 'विषय अभ्यास: तेलंगाना आंदोलन एवं राज्य पुनर्गठन',
    titleUrdu: 'موضوعاتی مشق: تلنگانہ تحریک اور تنظیم نو',
    examType: 'DAILY_QUIZ',
    durationMins: 25,
    totalMarks: 20,
    totalQuestions: 20,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'TELANGANA',
    isPremiumOnly: false,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'pyq-tslprb-si-2022',
    title: 'TSLPRB Police SI Prelims (PWT) 2022 Official Question Paper (Solved)',
    titleTelugu: 'తెలంగాణ పోలీస్ ఎస్సై ప్రిలిమ్స్ 2022 ఒరిజినల్ పేపర్ (సమాధానాలతో)',
    titleHindi: 'तेलंगाना पुलिस एसआई 2022 मूल प्रश्न पत्र (हल सहित)',
    titleUrdu: 'تلنگانہ پولیس ایس آئی 2022 اصل پرچہ حل شدہ',
    examType: 'PRELIMS_PWT',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'TELANGANA',
    isPremiumOnly: false,
    isPreviousPaper: true,
    year: 2022,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'pyq-appolice-si-2023',
    title: 'AP Police SI Prelims (PWT) 2023 Official Question Paper (Solved)',
    titleTelugu: 'ఆంధ్రప్రదేశ్ పోలీస్ ఎస్సై ప్రిలిమ్స్ 2023 ఒరిజినల్ పేపర్ (సమాధానాలతో)',
    titleHindi: 'आंध्र प्रदेश पुलिस एसआई 2023 मूल प्रश्न पत्र (हल सहित)',
    titleUrdu: 'آندھرا پردیش پولیس ایس آئی 2023 اصل پرچہ حل شدہ',
    examType: 'PRELIMS_PWT',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'ANDHRA_PRADESH',
    isPremiumOnly: false,
    isPreviousPaper: true,
    year: 2023,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'pyq-tslprb-si-2018',
    title: 'TSLPRB Police SI Prelims (PWT) 2018 Official Question Paper (Solved)',
    titleTelugu: 'తెలంగాణ పోలీస్ ఎస్సై ప్రిలిమ్స్ 2018 ఒరిజినల్ పేపర్ (సమాధానాలతో)',
    titleHindi: 'तेलंगाना पुलिस एसआई 2018 मूल प्रश्न पत्र (हल सहित)',
    titleUrdu: 'تلنگانہ پولیس ایس آئی 2018 اصل پرچہ حل شدہ',
    examType: 'PRELIMS_PWT',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'TELANGANA',
    isPremiumOnly: false,
    isPreviousPaper: true,
    year: 2018,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'fwe-paper-3-arithmetic-reasoning',
    title: 'Final Written Exam (FWE) Paper III: Arithmetic & Test of Reasoning',
    titleTelugu: 'ఫైనల్ రాత పరీక్ష పేపర్ III: అర్థమెటిక్ మరియు రీజనింగ్',
    titleHindi: 'मुख्य परीक्षा पेपर III: अंकगणित एवं रीजनिंग',
    titleUrdu: 'مینز امتحان پیپر III: ریاضی اور استدلال',
    examType: 'MAINS_PAPER_3_ARITHMETIC_REASONING',
    durationMins: 180,
    totalMarks: 200,
    totalQuestions: 200,
    negativeMarking: false,
    negativeMarkRate: 0,
    isBilingual: true,
    targetState: 'ALL_INDIA',
    isPremiumOnly: true,
    questions: SAMPLE_QUESTIONS,
  },
  {
    id: 'daily-rapid-quiz-today',
    title: 'Daily Rapid Fire Practice Quiz - General Studies & Polity (20 Qs)',
    titleTelugu: 'డైలీ రాపిడ్ ఫైర్ క్విజ్ - జనరల్ స్టడీస్ & పాలిటీ',
    titleHindi: 'दैनिक रैपिड फायर क्विज - सामान्य अध्ययन एवं राजव्यवस्था',
    titleUrdu: 'روزانہ کوئز - جنرل اسٹڈیز اور پولیٹی',
    examType: 'DAILY_QUIZ',
    durationMins: 20,
    totalMarks: 20,
    totalQuestions: 20,
    negativeMarking: true,
    negativeMarkRate: 0.25,
    isBilingual: true,
    targetState: 'ALL_INDIA',
    isPremiumOnly: false,
    questions: SAMPLE_QUESTIONS,
  }
];

export const MOCK_PREVIOUS_PAPERS: PreviousPaper[] = [
  {
    id: 'pyq_01',
    examId: 'pyq-tslprb-si-2022',
    title: 'TSLPRB Police Sub-Inspector (Civil/AR) Prelims 2022 Solved Paper',
    state: 'TELANGANA',
    year: 2022,
    examShift: 'Morning Session (10:00 AM - 1:00 PM)',
    totalMarks: 200,
    durationMins: 180,
    totalQuestions: 200,
    downloadPdfUrl: '/docs/TSLPRB_SI_2022_Official_Paper.pdf',
    isSolved: true,
  },
  {
    id: 'pyq_02',
    examId: 'pyq-appolice-si-2023',
    title: 'AP Police Sub-Inspector (Civil/APSP) Prelims 2023 Solved Paper',
    state: 'ANDHRA_PRADESH',
    year: 2023,
    examShift: 'Paper I (10:00 AM - 1:00 PM)',
    totalMarks: 200,
    durationMins: 180,
    totalQuestions: 200,
    downloadPdfUrl: '/docs/AP_Police_SI_2023_Official_Paper.pdf',
    isSolved: true,
  },
  {
    id: 'pyq_03',
    examId: 'pyq-tslprb-si-2018',
    title: 'TSLPRB Police Sub-Inspector (Civil/AR/TSSP) Prelims 2018 Solved Paper',
    state: 'TELANGANA',
    year: 2018,
    examShift: 'General Shift',
    totalMarks: 200,
    durationMins: 180,
    totalQuestions: 200,
    downloadPdfUrl: '/docs/TSLPRB_SI_2018_Official_Paper.pdf',
    isSolved: true,
  },
  {
    id: 'pyq_04',
    examId: 'pyq-appolice-si-2018',
    title: 'AP Police Sub-Inspector (Civil/AR) Prelims 2018 Solved Paper',
    state: 'ANDHRA_PRADESH',
    year: 2018,
    examShift: 'Paper I & II Combined',
    totalMarks: 200,
    durationMins: 180,
    totalQuestions: 200,
    downloadPdfUrl: '/docs/AP_Police_SI_2018_Official_Paper.pdf',
    isSolved: true,
  }
];

export const MOCK_USER_ATTEMPTS: UserAttempt[] = [
  {
    id: 'att_recent_01',
    userId: 'usr_candidate_9921',
    examId: 'tslprb-si-pwt-mock-01',
    examTitle: 'TSLPRB SI Preliminary Written Test (PWT) - Grand Mock 1',
    startedAt: '2026-09-28T14:30:00.000Z',
    completedAt: '2026-09-28T17:15:20.000Z',
    score: 146.5,
    totalMarks: 200,
    accuracy: 78.4,
    timeSpentSeconds: 9920,
    status: 'COMPLETED',
    stateRank: 142,
    answers: {
      'q_pwt_01': { selectedOption: 'B', isCorrect: true, timeTakenSeconds: 42, markedForReview: false },
      'q_pwt_02': { selectedOption: 'B', isCorrect: true, timeTakenSeconds: 78, markedForReview: false },
      'q_pwt_03': { selectedOption: 'A', isCorrect: true, timeTakenSeconds: 31, markedForReview: false },
      'q_pwt_04': { selectedOption: 'A', isCorrect: true, timeTakenSeconds: 55, markedForReview: false },
      'q_pwt_05': { selectedOption: 'A', isCorrect: true, timeTakenSeconds: 48, markedForReview: false },
    }
  },
  {
    id: 'att_past_02',
    userId: 'usr_candidate_9921',
    examId: 'daily-rapid-quiz-today',
    examTitle: 'Daily Rapid Fire Practice Quiz - General Studies & Polity',
    startedAt: '2026-09-27T08:15:00.000Z',
    completedAt: '2026-09-27T08:32:10.000Z',
    score: 17.25,
    totalMarks: 20,
    accuracy: 86.2,
    timeSpentSeconds: 1030,
    status: 'COMPLETED',
    stateRank: 89,
    answers: {}
  },
  {
    id: 'att_past_03',
    userId: 'usr_candidate_9921',
    examId: 'pyq-tslprb-si-2022',
    examTitle: 'TSLPRB SI Prelims 2022 Solved Paper',
    startedAt: '2026-09-25T11:00:00.000Z',
    completedAt: '2026-09-25T13:50:00.000Z',
    score: 138.0,
    totalMarks: 200,
    accuracy: 74.0,
    timeSpentSeconds: 10200,
    status: 'COMPLETED',
    stateRank: 210,
    answers: {}
  }
];

export const MOCK_SUBJECT_PERFORMANCE: SubjectPerformance[] = [
  {
    subject: 'Arithmetic & Mensuration',
    questionsAttempted: 120,
    correctAnswers: 98,
    accuracy: 81.6,
    averageTimeSeconds: 62,
    status: 'STRONG'
  },
  {
    subject: 'Test of Reasoning & Mental Ability',
    questionsAttempted: 110,
    correctAnswers: 92,
    accuracy: 83.6,
    averageTimeSeconds: 48,
    status: 'STRONG'
  },
  {
    subject: 'Telangana Movement & Statehood (1948-2014)',
    questionsAttempted: 95,
    correctAnswers: 74,
    accuracy: 77.8,
    averageTimeSeconds: 40,
    status: 'AVERAGE'
  },
  {
    subject: 'Indian Polity, Constitution & Police System',
    questionsAttempted: 105,
    correctAnswers: 86,
    accuracy: 81.9,
    averageTimeSeconds: 38,
    status: 'STRONG'
  },
  {
    subject: 'Indian History & Modern Freedom Movement',
    questionsAttempted: 80,
    correctAnswers: 52,
    accuracy: 65.0,
    averageTimeSeconds: 45,
    status: 'AVERAGE'
  },
  {
    subject: 'General Science & Forensic Applications',
    questionsAttempted: 70,
    correctAnswers: 41,
    accuracy: 58.5,
    averageTimeSeconds: 52,
    status: 'WEAK'
  }
];

export const OFFICIAL_PET_STANDARDS: PetStandard[] = [
  {
    eventType: 'RUN_1600M',
    label: '1600 Meters Run (Men)',
    gender: 'MALE',
    qualifyingStandard: 435, // 7 mins 15 seconds
    unit: 'seconds (MM:SS)',
    description: 'Mandatory qualifying event for Civil, AR, SAR CPL, and TSSP candidates. Must finish under 7:15.',
  },
  {
    eventType: 'RUN_800M',
    label: '800 Meters Run (Women)',
    gender: 'FEMALE',
    qualifyingStandard: 320, // 5 mins 20 seconds
    unit: 'seconds (MM:SS)',
    description: 'Mandatory qualifying event for Women SI candidates. Must finish under 5:20.',
  },
  {
    eventType: 'LONG_JUMP',
    label: 'Long Jump (Men: 3.80m / Women: 2.75m)',
    gender: 'MALE',
    qualifyingStandard: 3.80,
    unit: 'meters',
    description: 'Official qualifying standard for Men is 3.80 meters. Max 3 attempts provided.',
  },
  {
    eventType: 'SHOT_PUT',
    label: 'Shot Put (7.26 kg for Men / 4 kg for Women)',
    gender: 'MALE',
    qualifyingStandard: 5.60,
    unit: 'meters',
    description: '7.26 kg shot put. Qualifying distance is 5.60 meters. AR candidates gain bonus marks above 6.5m.',
  },
  {
    eventType: 'SPRINT_100M',
    label: '100 Meters Sprint',
    gender: 'MALE',
    qualifyingStandard: 15.00,
    unit: 'seconds',
    description: 'Speed benchmark sprint. Must complete within 15.00 seconds.',
  },
];

export const INITIAL_PET_LOGS: PetLogEntry[] = [
  {
    id: 'pet_01',
    userId: 'usr_candidate_9921',
    eventType: 'RUN_1600M',
    metricValue: 412, // 6 mins 52 sec
    unit: 'seconds',
    loggedDate: '2026-09-26',
    isQualified: true,
    notes: 'Morning ground session at Gachibowli Stadium. Completed in 6:52 min.',
  },
  {
    id: 'pet_02',
    userId: 'usr_candidate_9921',
    eventType: 'LONG_JUMP',
    metricValue: 4.15, // 4.15m
    unit: 'meters',
    loggedDate: '2026-09-25',
    isQualified: true,
    notes: 'Took 3 attempts. Best jump was 4.15 meters on the third try.',
  },
  {
    id: 'pet_03',
    userId: 'usr_candidate_9921',
    eventType: 'SHOT_PUT',
    metricValue: 6.20, // 6.20m
    unit: 'meters',
    loggedDate: '2026-09-24',
    isQualified: true,
    notes: 'Solid throw with 7.26kg iron ball.',
  },
  {
    id: 'pet_04',
    userId: 'usr_candidate_9921',
    eventType: 'SPRINT_100M',
    metricValue: 13.85,
    unit: 'seconds',
    loggedDate: '2026-09-22',
    isQualified: true,
    notes: 'Good start from blocks. 13.85s.',
  },
];

export const INITIAL_DESCRIPTIVE_SUBMISSIONS: DescriptiveSubmission[] = [
  {
    id: 'desc_sub_101',
    userId: 'usr_candidate_9921',
    candidateName: 'Vasu Reddy',
    candidateRoll: 'TS-SI-2026-8841',
    paperType: 'PAPER_I_ENGLISH',
    topic: 'Role of Artificial Intelligence and Predictive Policing in Curbing Cyber Crime',
    typedContent: `In the contemporary era of exponential digital expansion, law enforcement agencies are confronted with unprecedented challenges in combating cyber crimes. Artificial Intelligence (AI) and Machine Learning (ML) algorithms have emerged as potent investigative catalysts. 

From analyzing call detail records (CDR) and IP tracking to predictive hot-spot policing, modern state police forces such as Telangana Police's TS-Cyber Security Bureau (TSCSB) have set benchmarks. However, strict adherence to constitutional safeguards under Article 21, data privacy standards, and procedural fairness must remain the bedrock of technology-driven policing. Police Sub-Inspectors serve as the first line of response, making technological literacy and forensic precision indispensable virtues.`,
    submittedAt: '2026-09-27 18:30',
    status: 'EVALUATED',
    marksAwarded: 41,
    maxMarks: 50,
    evaluatorRemarks: 'Exceptional structural clarity. Good synthesis of legal provisions (Article 21) and real police initiatives like TSCSB. Minor vocabulary refinement recommended in paragraph 2.',
    rubricScores: {
      contentRelevance: 13,
      vocabularyGrammar: 12,
      organizationStructure: 8,
      expressionStyle: 8,
    }
  },
  {
    id: 'desc_sub_102',
    userId: 'usr_candidate_4412',
    candidateName: 'K. Sai Kiran',
    candidateRoll: 'TS-SI-2026-3112',
    paperType: 'PAPER_II_TELUGU',
    topic: 'తెలంగాణ గ్రామీణ ప్రాంతాలలో ఫ్రెండ్లీ పోలీసింగ్ విధానం - ఫలితాలు (Friendly Policing in Rural Telangana)',
    typedContent: 'తెలంగాణ రాష్ట్రంలో అమలు చేయబడుతున్న ఫ్రెండ్లీ పోలీసింగ్ విధానం గ్రామీణ ప్రజలు మరియు పోలీసు వ్యవస్థ మధ్య ఉన్న దూరాన్ని తగ్గించడంలో విశేష పాత్ర పోషిస్తున్నది...',
    submittedAt: '2026-09-28 11:15',
    status: 'PENDING_REVIEW',
    maxMarks: 50,
  }
];

export const INITIAL_LEADERBOARD: LeaderboardRank[] = [
  {
    rank: 1,
    userId: 'usr_cand_01',
    name: 'B. Manoj Kumar',
    rollNumber: 'TS-SI-2026-1029',
    targetState: 'TELANGANA',
    score: 184.5,
    accuracy: 94.2,
    timeTakenMins: 162,
  },
  {
    rank: 2,
    userId: 'usr_cand_02',
    name: 'P. Sneha Latha',
    rollNumber: 'AP-SI-2026-5514',
    targetState: 'ANDHRA_PRADESH',
    score: 181.0,
    accuracy: 92.5,
    timeTakenMins: 168,
  },
  {
    rank: 3,
    userId: 'usr_candidate_9921',
    name: 'Vasu Reddy',
    rollNumber: 'TS-SI-2026-8841',
    targetState: 'TELANGANA',
    score: 178.5,
    accuracy: 91.0,
    timeTakenMins: 170,
  },
  {
    rank: 4,
    userId: 'usr_cand_04',
    name: 'Ch. Venkat Rao',
    rollNumber: 'TS-SI-2026-9042',
    targetState: 'TELANGANA',
    score: 174.0,
    accuracy: 88.6,
    timeTakenMins: 174,
  },
  {
    rank: 5,
    userId: 'usr_cand_05',
    name: 'G. Harish Naidu',
    rollNumber: 'AP-SI-2026-7832',
    targetState: 'ANDHRA_PRADESH',
    score: 171.5,
    accuracy: 87.9,
    timeTakenMins: 175,
  },
  {
    rank: 6,
    userId: 'usr_cand_06',
    name: 'M. Divya Jyothi',
    rollNumber: 'TS-SI-2026-4431',
    targetState: 'TELANGANA',
    score: 169.0,
    accuracy: 86.4,
    timeTakenMins: 178,
  },
];
